# Site settings
title: Augmented Humans Conference 2020
email: info@dfki.de
url: http://augmented-humans.org
description: "The Augmented Humans (AH) International Conference will be held in Kaiserslautern, Germany, on March 16-18, 2020, focusing on physical, cognitive, and perceptual augmenting humans through digital technologies."
keywords: "Augmented Human, HCI, Human Computer Integration, Computer Science"
meta_author: Augmented Humans

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)

#Google Analytics
google_analytics: 

# Build settings
plugins: [jekyll-paginate, jekyll-feed]

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 7
paginate_path: "/news/page:num/"

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]