# Site settings
title: Augmented Humans Conference 2020
email: info@dfki.de
url: https://augmented-humans.org
description: "The Augmented Humans (AH) International Conference will be held in Kaiserslautern, Germany, on March 16-17, 2020, focusing on physical, cognitive, and perceptual augmenting humans through digital technologies."
keywords: "Augmented Human, HCI, Human Computer Integration, Computer Science"
meta_author: Augmented Humans

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)

# Build settings
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 7
paginate_path: "/blog/page:num/"
defaults: 
  - scope:
      path: "img/posts/**"
      path: "sessions/**"
    values:
      sitemap: false

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]